### ISSUE TITLE
My Streamlit Session was Terminated

### ISSUE THREAD

**Issue by bandari-thiru** [streamlit/st-issues#8]
Hi All
[logs.txt](https://github.com/streamlit/st-issues/files/13556938/logs.txt)

I am facing one issue in streamlit. The session was terminated after run a python file. 
I have uploaded the trace files too for further analysis. 

Please help me to overcome this issue.

Regards
Sudhakar B

**Comment by LukasMasuch** [comment]
Closing this. Please report issues to the main Streamlit repository: https://github.com/streamlit/streamlit/issues
